---
- name: add deadsnakes ppa on xenial
  apt_repository:
    repo: ppa:deadsnakes/ppa
    filename: deadsnakes
    mode: 0644
  when: ansible_lsb.codename == 'xenial'
  tags:
    - srv_dyndns_install
    - srv_dyndns_python38

- name: install python3.8
  apt:
    name:
      - python3.8
      - python3.8-dev
      - python3.8-venv
  tags:
    - srv_dyndns_install
    - srv_dyndns_python38

- name: install pip requirements for dyndns
  pip:
    name:
      - cloudflare
      - pysocks
      - paramiko
      - cryptography < 3.4
    virtualenv: /usr/local/dyndns
    virtualenv_command: python3.8 -m venv
  tags:
    - srv_dyndns_install

- name: install dyndns server executable
  copy:
    src: dyndns.py
    dest: /usr/local/sbin/dyndns
    force: true
    mode: 0755
  notify: restart dyndns service
  tags:
    - srv_dyndns_install
    - srv_dyndns_script
    - srv_dyndns_service

- block:
    - name: detect home directory of dyndns user
      user:
        name: "{{ srv_dyndns_service_user }}"
      register: dyndns_user

    - name: make directory for dyndns ssh key
      file:
        path: "{{ dyndns_user.home }}/.ssh"
        state: directory
        owner: "{{ dyndns_user.name }}"
        group: "{{ dyndns_user.group }}"
        mode: 0700

    - name: install ssh key for dyndns login
      copy:
        src: "{{ srv_dyndns_ssh_keyfile }}"
        dest: "{{ dyndns_user.home }}/.ssh/dyndns.key"
        owner: "{{ dyndns_user.name }}"
        group: "{{ dyndns_user.group }}"
        mode: 0600
      notify: restart dyndns service
  when:
    - srv_dyndns_service_user |d('')
    - srv_dyndns_ssh_keyfile |d('')
  tags: srv_dyndns_keyfile

- name: configure dyndns service
  template:
    src: dyndns.conf
    dest: /etc/dyndns.conf
    mode: 0640
    owner: "{{ srv_dyndns_service_user |d('root', true) }}"
    group: sudo
  vars:
    ssh_url: "{{ srv_dyndns_ssh_url |default('',true) }}"
    got_keyfile: "{{ srv_dyndns_service_user and srv_dyndns_ssh_keyfile }}"
    keyfile: "{{ '~/.ssh/dyndns.key' if got_keyfile else '' }}"
  notify: restart dyndns service
  tags:
    - srv_dyndns_config
    - srv_dyndns_keyfile
    - srv_dyndns_service

- name: setup dyndns systemd service
  template:
    src: dyndns.service
    dest: /etc/systemd/system/dyndns.service
    mode: 0644
  register: dyndns_service_file
  notify: restart dyndns service
  tags: srv_dyndns_service

- name: activate dyndns systemd service
  systemd:
    name: dyndns
    state: started
    enabled: true
    daemon_reload: "{{ dyndns_service_file is changed }}"
  tags: srv_dyndns_service

- name: directory for nginx dyndns mixin
  file:
    path: /etc/nginx/mixin.d
    state: directory
    mode: 0755
  tags: srv_dyndns_nginx

- name: configure nginx redirector for dyndns
  template:
    src: dyndns.nginx.conf
    dest: /etc/nginx/mixin.d/dyndns.conf
    mode: 0644
  notify: reload nginx service
  tags: srv_dyndns_nginx
...
