---
is_permitted: false
lin_firewall: none
allow_sysctl: false
lin_core_time_sync: false
lin_core_system_locale: en_US.UTF-8
lin_use_ssh: "{{ lookup('env','IVATEST_SSH_SERVER')|d('true',true)|bool }}"
...
